USE Bolnica
GO

INSERT INTO Drzava(Naziv) VALUES ('Hrvatska')
INSERT INTO Drzava(Naziv) VALUES ('Slovenija')
INSERT INTO Drzava(Naziv) VALUES ('Bosna i Hercegovina')
INSERT INTO Drzava(Naziv) VALUES ('Republika srpska')

INSERT INTO Grad(Naziv,PostanskiBroj,DrzavaId) 
VALUES ('Zagreb','10000',1)
INSERT INTO Grad(Naziv,PostanskiBroj,DrzavaId) 
VALUES ('Varazdin','42000',1)
INSERT INTO Grad(Naziv,PostanskiBroj,DrzavaId) 
VALUES ('Split','21000',1)

INSERT INTO Osoba VALUES ('Dino','Novosel','18503473191')
INSERT INTO Osoba VALUES ('Ana','Anic','61155689953')
INSERT INTO Osoba VALUES ('Pero','Peric','55008004255')

INSERT INTO Osoba VALUES ('Vito','Martinkovic','07287782296')
INSERT INTO Osoba VALUES ('Toni','Martinkovic','44244833360')
INSERT INTO Osoba VALUES ('Domagoj','Dragicevic','95384100416')

INSERT INTO Osoba VALUES ('Simona','Gotovac','78161854742')
INSERT INTO Osoba VALUES ('Ava','Karabatic','45737552614')
INSERT INTO Osoba VALUES ('Severina','Kojic','17546141320')

INSERT INTO Osoba VALUES ('Danko','Horvat','05822617880')
INSERT INTO Osoba VALUES ('Deni','Kupres','03889016660')

INSERT INTO RadnoMjesto(Naziv,Titula) VALUES ('Doktor opce prakse','dr.')
INSERT INTO RadnoMjesto(Naziv,Titula) VALUES ('Specijalist','dr. spec.')
INSERT INTO RadnoMjesto(Naziv,Titula) VALUES ('Medicinska sestra','med. sestra')
INSERT INTO RadnoMjesto(Naziv,Titula) VALUES ('Domar',NULL)
INSERT INTO RadnoMjesto(Naziv,Titula) VALUES ('Vozac',NULL)

INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('iH223k4GMoPcNq',1,1,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('epiesk22y59XG6',2,1,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('iUgYVIc4xop2ma',3,1,10000)

INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('4axE2Gfg8eJvUZ',4,2,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('Mhzv2NWa5pxLzf',5,2,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('7ZSQwX3xn9UsU1',6,2,10000)

INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('1KgYlWDVzQI05C',7,3,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('FVgdcmjfvE5lTs',8,3,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('d3WrM35WzX1rXL',9,3,10000)

INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('8rEiVpgaCLT0TQ',10,4,10000)
INSERT INTO Zaposlenik(SifraZaposlenika,OsobaId,RadnoMjestoId,Placa) 
VALUES ('TC72kl45Yxl8Y9',11,5,10000)

INSERT INTO TipTretmana(Naziv) VALUES ('Operacija')
INSERT INTO TipTretmana(Naziv) VALUES ('Masaza')
INSERT INTO TipTretmana(Naziv) VALUES ('Voznja')

INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Acido-bazična ravnoteža',46.97)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Alfa-1-antitripsin - fenotipizacija',485.37)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Folna kiselina',66.25)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Glukoza',14.87)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Kloridi',16.22)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Lipaza ',20.28)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Magnezij',17.58 )
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Natrij u mokraci',19.60)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Osteokalcin',109.51)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Serotonin u trombocitima',275.13)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Trigliceridi',16.90)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Urat',15.55)
INSERT INTO LabaratorijskoTestiranje(Naziv,Cijena)
VALUES('Zeljezo',75.04)


INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Pantoprazol','Belupo d.d.',139.99)
INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Inzulin','Eli Lilly Nederland B.V.',49.99)
INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Glimepirid','PLIVA HRVATSKA d.o.o.',229.99)
INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Nadroparin','Aspen Pharma Trading Limited',399.99)
INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Pantoprazol','Belupo d.d.',139.99)
INSERT INTO Lijek(Naziv,Proizvodac,Cijena)
VALUES ('Infuzija','Bolnica d.d.o.',139.99)
